### ISSUE TITLE
accessing injected services in ExecuteSectionAsync does not work

### ISSUE THREAD

**Issue by ivanjx** [DamianEdwards/RazorSlices#72]
i tried this:
```cshtml
@inject ILocalizerService L

<p>@L[Model.Language, "content"]</p>

@function {
    protected override Task ExecuteSectionAsync(string name)
    {
        string preheader = L[Model.Language, "password_reset_preheader"];
        
        if (name == "preheader")
        {
            <p>@preheader</p>
        }

        return Task.CompletedTask;
    }
}
```

it throws:
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at AspNetCoreGeneratedDocument.Resources_EmailTemplates_PasswordRecovery.ExecuteSectionAsync(String name) in /x/PasswordRecovery.cshtml:line 30
   at RazorSlices.RazorLayoutSlice`1.RenderSectionAsync(String sectionName) in /_/src/RazorSlices/RazorLayoutSliceOfTModel.cs:line 44
   at AspNetCoreGeneratedDocument.Resources_EmailTemplates_Root.ExecuteAsync()
   at RazorSlices.RazorSlice.AwaitExecuteTaskFlushAndDispose(RazorSlice slice, Task executeTask) in /_/src/RazorSlices/RazorSlice.cs:line 256
   at RazorSlices.RazorSliceStringBuilderExtensions.AwaitRenderTask(ValueTask task, StringBuilder sb) in /_/src/RazorSlices/RazorSlice.StringBuilderExtensions.cs:line 50
   at x.UserPasswordRecoveryMailGeneratorService.GenerateAsync(String language, String link) in /x/UserAuthentication/UserPasswordRecoveryMailGeneratorService.cs:line 43
   at x.GenerateAsyncTest()
```

works fine if the `ExecuteSectionAsync` do not access any injected services.

**Comment by DamianEdwards** [comment]
Thanks for the report, I'll take a look.

**Comment by ivanjx** [comment]
first of all thank you for fixing this.
is there an ETA on when this will be released into nuget?

**Comment by DamianEdwards** [comment]
I'm working on one more thing before I cut the next release. Could be as soon as today depending on how it goes.

**Comment by DamianEdwards** [comment]
@ivanjx this is now available at https://www.nuget.org/packages/RazorSlices/0.9.0

Let me know if you have any issues!

**Comment by ivanjx** [comment]
works perfectly. thanks!
